version: "3.7"
services:
    db:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
        - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
        - fractal

    fractal-backend:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
        - .env
        volumes:
        - ./fractal-backend:/var/www/html
        networks:
        - fractal
        ports:
        - 8000:8000

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: ${DB_HOST}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
        - 8080:8080
        networks:
        - fractal


networks:
    fractal:
        driver: bridge